AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: false

  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 120

Layout/EndOfLine:
  Enabled: False

Metrics/MethodLength:
  Max: 45

Metrics/AbcSize:
  Max: 55

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 11

Metrics/ParameterLists:
  Max: 7

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*/spec/**/*.rb'

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/YodaExpression:
  Enabled: false
